# Generated by Django 5.1.2 on 2026-09-24 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='thumbnail',
            new_name='image_choice1',
        ),
        migrations.AddField(
            model_name='post',
            name='image_choice2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
